/**
 * Atomic ticket key allocation.
 *
 * Keys were generated by reading the highest existing key for the month and
 * adding one:
 *
 *     const latest = await SupportTicket.getLatestKey(prefix);   // SC-202608-0007
 *     sequence = parseInt(latest.split('-')[2], 10) + 1;         // 8
 *
 * Two callers that read before either writes both compute 8, and the second
 * insert violates the unique constraint on ticket_key — or worse, if that
 * constraint were ever relaxed, silently duplicates. It has been latent because
 * humans click a button one at a time. A retrying machine client will hit it,
 * so this is fixed before the integration API exists rather than after.
 *
 * A counter row per month prefix, incremented in a single statement, serialises
 * allocation. Concurrent callers queue on the row lock rather than racing.
 *
 * Additive and idempotent.
 *
 *   node migrate_ticket_sequences.js
 */

require('dotenv').config({ path: require('path').join(__dirname, '.env') });
const db = require('./db');

async function migrate() {
    const client = await db.pool.connect();
    try {
        await client.query('BEGIN');

        console.log('1. Creating ticket_sequences...');
        await client.query(`
            CREATE TABLE IF NOT EXISTS ticket_sequences (
                prefix     VARCHAR(20) PRIMARY KEY,   -- e.g. SC-202608
                last_value INTEGER NOT NULL DEFAULT 0,
                updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
            );
        `);

        console.log('2. Seeding from existing ticket keys...');
        // Highest number already used per prefix, so the first allocation after
        // this migration cannot collide with a key issued before it.
        const seeded = await client.query(`
            INSERT INTO ticket_sequences (prefix, last_value)
            SELECT substring(ticket_key from 1 for 9) AS prefix,
                   max(NULLIF(regexp_replace(split_part(ticket_key, '-', 3), '\\D', '', 'g'), '')::int) AS last_value
            FROM support_tickets
            WHERE ticket_key ~ '^SC-[0-9]{6}-[0-9]+$'
            GROUP BY 1
            ON CONFLICT (prefix) DO UPDATE
                SET last_value = GREATEST(ticket_sequences.last_value, EXCLUDED.last_value),
                    updated_at = CURRENT_TIMESTAMP
            RETURNING prefix, last_value
        `);

        for (const r of seeded.rows) console.log(`   ${r.prefix} -> ${r.last_value}`);
        if (!seeded.rows.length) console.log('   no existing tickets to seed from');

        await client.query('COMMIT');
    } catch (err) {
        await client.query('ROLLBACK');
        console.error('❌ Migration failed, rolled back:', err.message);
        throw err;
    } finally {
        client.release();
    }

    // Outside the transaction: a summary failure must never print "rolled back"
    // over work that already committed.
    try {
        const { rows } = await db.query('SELECT prefix, last_value FROM ticket_sequences ORDER BY prefix');
        console.log('\n✅ Ticket sequence migration complete.');
        console.log(`   ${rows.length} prefix counter(s) tracked.`);
    } catch (err) {
        console.warn('\n⚠️  Migration succeeded, but the summary failed:', err.message);
    }
}

migrate()
    .then(() => db.pool.end())
    .catch(async () => { try { await db.pool.end(); } catch { /* closing */ } process.exit(1); });
